### ISSUE TITLE
[Bug]: `ng test` does not work for o3r-generated library in pnp

### ISSUE THREAD

**Issue by cpaulve-1A** [AmadeusITGroup/otter#2620]
### Package name

workspace

### Package version

11.5.0

### Reproduction steps

Generate an o3r project with yarn as packageManager and generate a library.
Run `yarn ng test my-lib`. Test should work.
Update the `yarnrc` to set `nodeLinker: pnp` and run the yarn install.
Now, run the test command. 

### Current result

Test fails with error:
`Error: error TS2688: Cannot find type definition file for 'jasmine'.
  The file is in the program because:
    Entry point of type library 'jasmine' specified in compilerOptions
`
and errors such as `Cannot find name 'beforeEach'`.

### Expected result

Test should not fail

### Additional comments

Issue seems to come from the fact that jasmine is not part of the devDependencies of the library project and is only available in the root package and that the project is in pnp with defined workspace.
Yarn pnp expects that each module works in isolation and the generated library misses the `@types/jasmine` devDependency.
(See https://github.com/yarnpkg/berry/issues/1058#issuecomment-604993997)
 
We need to keep in mind that we cannot just add this devDependency as it was brought by angular create and library generator. It is not recommended to add dependencies that we do not bring ourselves.

In this issue, we need to consider whether we keep the support of pnp for our generated module, if we remove the workspace property from the generated root package.json (and see the impact on project size et dev experience) or if we can find an alternative solution.

**Comment by cpaulve-1A** [comment]
As discussed, we will fix this issue by removing the jasmine setup and replace it with jest in the application and library generation.

**Comment by malek-benazzouz** [comment]
The following two items should also be considered when putting in place the setup.

1. Today, when generating a project then generating an application using Jest setup, the setup is partially done:
    * `npm test` command will run the tests using jest
    * `ng test` command will run the tests using jasmine

3. Today, in the generated app `tsconfig.spec.json` file, we can see the following setting: `compilerOptions.types: ["jasmine"]`. We probably want to replace that by `compilerOptions.types: ["node", "jest"]`, for example by generating a root `tsconfig.jest.json` and extending this file in the app/lib `tsconfig.spec.json`.
